DELETE FROM CUSTOMERS WHERE CITY='BOMBAY'
SELECT * FROM CUSTOMERS
DELETE FROM DEPOSIT WHERE AMOUNT<=1000
SELECT * FROM DEPOSIT
DELETE FROM BORROW WHERE BNAME='AJNI'
SELECT * FROM BORROW
DELETE FROM BORROW WHERE LOANNO BETWEEN 201 AND 210
DELETE FROM DEPOSIT WHERE ADATE>'1996-01-12'
TRUNCATE TABLE CUSTOMERS
DELETE FROM DEPOSIT WHERE ACTNO=101 AND CNAME='ANIL'
DELETE FROM DEPOSIT WHERE BNAME<>'ANDHERI'
DELETE FROM BORROW WHERE AMOUNT<2000 AND BNAME<>'VRCE'
DROP TABLE BRANCH