SELECT * FROM STUDENT1 WHERE DID = (SELECT DID FROM DEPARTMENT WHERE DNAME='COMPUTER')
SELECT NAME FROM STUDENT1 WHERE RNO IN (SELECT RNO FROM ACADEMIC WHERE SPI>8)
SELECT * FROM STUDENT1 WHERE DID =(SELECT DID FROM DEPARTMENT WHERE DNAME='COMPUTER') AND CITY='RAJKOT'
SELECT COUNT(*) FROM STUDENT1 WHERE DID =(SELECT DID FROM DEPARTMENT WHERE DNAME='ELECTRICAL')
SELECT NAME FROM STUDENT1 WHERE RNO IN(SELECT RNO FROM ACADEMIC WHERE SPI =(SELECT MAX(SPI) FROM ACADEMIC))
SELECT * FROM STUDENT1 WHERE RNO IN (SELECT RNO FROM ACADEMIC WHERE BKLOG>1)
SELECT NAME FROM STUDENT1 WHERE RNO =(SELECT RNO FROM ACADEMIC WHERE SPI =(SELECT MAX(SPI) FROM ACADEMIC 
WHERE SPI< (SELECT MAX(SPI) FROM ACADEMIC)))
SELECT NAME FROM STUDENT1 WHERE DID IN (SELECT DID FROM DEPARTMENT WHERE DNAME IN('MECHANICAL','COMPUTER'))
SELECT NAME FROM STUDENT1 WHERE DID=(SELECT DID FROM STUDENT1 WHERE RNO=102)
SELECT NAME FROM STUDENT1 WHERE RNO IN(SELECT RNO FROM ACADEMIC WHERE SPI>9)AND
DID IN (SELECT DID FROM DEPARTMENT WHERE DNAME='ELECTRICAL')