SELECT GETDATE() AS TODAY_DATE
SELECT GETDATE()+365
SELECT CONVERT(VARCHAR(50),GETDATE())
SELECT CONVERT(VARCHAR(50),GETDATE(),106) 
SELECT CONVERT(VARCHAR(50),GETDATE(),7) 
SELECT DATEDIFF(MONTH,'31-DEC-08','31-MAR-09')
SELECT DATEDIFF(YEAR,'25-JAN-12','14-SEP-10')
SELECT DATEDIFF(HOUR,'2012-01-25 07:00','2010-09-14 10:30')
SELECT DAY('12-MAY-16'),MONTH('12-MAY-16'),YEAR('12-MAY-16')
SELECT GETDATE()+(365*5)
SELECT GETDATE()-60
SELECT DATEADD(MONTH,2,GETDATE())
SELECT DATENAME(MONTH,GETDATE())
SELECT DATEPART(MONTH,GETDATE())
SELECT EOMONTH(GETDATE())
SELECT DATEADD(DAY,30,GETDATE())
SELECT DATEDIFF(YEAR,'2003-07-15',GETDATE())
-----------------------------------------------------------------------------
SELECT COUNT(SID) FROM STUDENT_MARKS 
SELECT SUM(MARKS) FROM STUDENT_MARKS 
SELECT AVG(MARKS) FROM STUDENT_MARKS 
SELECT MIN(MARKS) FROM STUDENT_MARKS 
SELECT MAX(MARKS) FROM STUDENT_MARKS 
--------------------------------------------------------------------------------


