SELECT NAME FROM COMPUTER 
UNION 
SELECT NAME FROM ELECTRICAL
SELECT NAME FROM COMPUTER 
UNION ALL
SELECT NAME FROM ELECTRICAL
SELECT NAME FROM COMPUTER 
INTERSECT 
SELECT NAME FROM ELECTRICAL
SELECT NAME FROM COMPUTER 
EXCEPT
SELECT NAME FROM ELECTRICAL
SELECT NAME FROM ELECTRICAL
EXCEPT
SELECT NAME FROM COMPUTER
SELECT * FROM COMPUTER 
UNION 
SELECT * FROM ELECTRICAL
SELECT * FROM COMPUTER 
INTERSECT
SELECT * FROM ELECTRICAL
--------------------------------------------------------------------------------
SELECT * INTO WORLDCUP FROM CRICKET
SELECT * FROM WORLDCUP
SELECT NAME,CITY INTO T20 FROM CRICKET WHERE 1<>1
SELECT * FROM T20
SELECT * INTO IPL FROM CRICKET WHERE 1<>1
INSERT INTO IPL  SELECT * FROM CRICKET WHERE NAME LIKE'_A%'
TRUNCATE TABLE IPL
DELETE FROM CRICKET WHERE CITY='JHARKHAND'
SP_RENAME 'IPL','IPL2018'
DROP TABLE T20
-----------------------------------------------------------------------------------