SELECT * FROM STUDENT CROSS JOIN RESULT
--------------------------
SELECT STUDENT.RNO,NAME,BRANCH,SPI 
FROM STUDENT
LEFT OUTER JOIN RESULT
ON STUDENT.RNO=RESULT.RNO
WHERE STUDENT.BRANCH='CE'
-------------------------
SELECT STUDENT.RNO,NAME,BRANCH,SPI 
FROM STUDENT
LEFT OUTER JOIN RESULT
ON STUDENT.RNO=RESULT.RNO
WHERE STUDENT.BRANCH<>'EC
------------------------'
SELECT BRANCH,AVG(SPI) AS AVERAGE FROM STUDENT
INNER JOIN RESULT 
ON STUDENT.RNO=RESULT.RNO
GROUP BY BRANCH
-------------------------
SELECT BRANCH,AVG(SPI) AS AVERAGE FROM STUDENT
INNER JOIN RESULT 
ON STUDENT.RNO=RESULT.RNO
GROUP BY BRANCH,SPI
ORDER BY SPI
----------------
SELECT BRANCH,AVG(SPI) AS AVERAGE FROM STUDENT
INNER JOIN RESULT 
ON STUDENT.RNO=RESULT.RNO
WHERE BRANCH IN('CE','ME')
GROUP BY BRANCH
---------------------
SELECT STUDENT.RNO,NAME,BRANCH FROM STUDENT
LEFT OUTER JOIN RESULT
ON STUDENT.RNO=RESULT.RNO
---------------------
SELECT STUDENT.RNO,NAME,BRANCH FROM STUDENT
RIGHT OUTER JOIN RESULT
ON STUDENT.RNO=RESULT.RNO
----------------------------
SELECT STUDENT.RNO,NAME,BRANCH,SPI FROM STUDENT
FULL OUTER JOIN RESULT
ON STUDENT.RNO=RESULT.RNO
--------------------------------
SELECT E.NAME,M.NAME FROM EMP E
LEFT OUTER JOIN EMP M
ON E.MNO=M.ENO
-----------------------------------