CREATE TABLE STUDENTS(
STUID INT,
FIRSTNAME VARCHAR(25),
LASTNAME VARCHAR(25),
WEBSITE VARCHAR(50),
CITY VARCHAR(25),
DIVISION VARCHAR(20)
)
INSERT INTO STUDENTS VALUES(1011,'KEYUR','PATEL','TECHONTHENET.COM','RAJKOT','II-BCX')
INSERT INTO STUDENTS VALUES(1022,'HARDIK','SHAH','DIGMINECRAFT.COM','AHEMDABAD','I-BCY')
INSERT INTO STUDENTS VALUES(1033,'KAJAL','TRIVEDI','BIGACTIVITIES.COM','BARODA','IV-DCX')
INSERT INTO STUDENTS VALUES(1044,'BHOOMI','GAJERA','CHECKYOURMATH.COM','AHEMDABAD','III-DCW')
INSERT INTO STUDENTS VALUES(1055,'HARMIT','MITEL',NULL,'RAJKOT','II-BCY')
INSERT INTO STUDENTS VALUES(1066,'ASHOK','JANI',NULL,'BARODA','II-BCZ')

SELECT FIRSTNAME FROM STUDENTS WHERE FIRSTNAME LIKE'K%'
SELECT FIRSTNAME FROM STUDENTS WHERE FIRSTNAME LIKE'_____'
SELECT FIRSTNAME,LASTNAME FROM STUDENTS WHERE CITY LIKE '_____A'
SELECT FIRSTNAME FROM STUDENTS WHERE LASTNAME LIKE'%TEL'
SELECT FIRSTNAME FROM STUDENTS WHERE FIRSTNAME LIKE'HA%T'
SELECT FIRSTNAME FROM STUDENTS WHERE FIRSTNAME LIKE 'K_Y%'
SELECT FIRSTNAME FROM STUDENTS WHERE WEBSITE IS NULL AND FIRSTNAME LIKE '_____'
SELECT FIRSTNAME FROM STUDENTS WHERE LASTNAME LIKE'%JER%'
SELECT FIRSTNAME FROM STUDENTS WHERE CITY LIKE 'R%' OR CITY LIKE 'B%'
SELECT FIRSTNAME FROM STUDENTS WHERE WEBSITE  IS NOT NULL
SELECT FIRSTNAME FROM STUDENTS WHERE FIRSTNAME LIKE'[A-H]%'
SELECT FIRSTNAME FROM STUDENTS WHERE FIRSTNAME LIKE '_[A,E,I,O,U]%'
SELECT FIRSTNAME FROM STUDENTS WHERE CITY LIKE'%ROD%'
SELECT FIRSTNAME,LASTNAME FROM STUDENTS WHERE WEBSITE LIKE'BI%'
SELECT CITY FROM STUDENTS WHERE LASTNAME LIKE'______'
SELECT FIRSTNAME FROM STUDENTS WHERE CITY LIKE '_____' AND CITY NOT LIKE'BA%'
SELECT FIRSTNAME FROM STUDENTS WHERE DIVISION LIKE'II%'
SELECT FIRSTNAME FROM STUDENTS WHERE DIVISION LIKE'%BC%'
SELECT STUID,CITY FROM STUDENTS WHERE DIVISION LIKE'______' AND WEBSITE IS NOT NULL
SELECT * FROM STUDENTS WHERE FIRSTNAME  NOT LIKE'__[A,E,I,O,U]%'